
SET(WRAPPER_AUTO_INCLUDE_HEADERS OFF)
WRAP_INCLUDE("itkNarrowBand.h")

WRAP_CLASS("itk::BandNode")
  FOREACH(d ${WRAP_ITK_DIMS})
    WRAP_TYPES("I${d}${ITKM_D}"  "itk::Index < ${d} >, ${ITKT_D}"  "D")
    WRAP_TYPES("I${d}${ITKM_F}"  "itk::Index < ${d} >, ${ITKT_F}"  "F")
    WRAP_TYPES("I${d}${ITKM_UL}" "itk::Index < ${d} >, ${ITKT_UL}" "UL")
    WRAP_TYPES("I${d}${ITKM_US}" "itk::Index < ${d} >, ${ITKT_US}" "US")
    WRAP_TYPES("I${d}${ITKM_UC}" "itk::Index < ${d} >, ${ITKT_UC}" "UC")
    WRAP_TYPES("I${d}${ITKM_SL}" "itk::Index < ${d} >, ${ITKT_SL}" "SL")
    WRAP_TYPES("I${d}${ITKM_SS}" "itk::Index < ${d} >, ${ITKT_SS}" "SS")
    WRAP_TYPES("I${d}${ITKM_SC}" "itk::Index < ${d} >, ${ITKT_SC}" "SC")
  ENDFOREACH(d)
END_WRAP_CLASS()

WRAP_CLASS("itk::NarrowBand" POINTER)
  FOREACH(d ${WRAP_ITK_DIMS})
    WRAP_TYPES("BNI${d}${ITKM_D}"  "itk::BandNode< itk::Index < ${d} >, ${ITKT_D} >"  "D")
    WRAP_TYPES("BNI${d}${ITKM_F}"  "itk::BandNode< itk::Index < ${d} >, ${ITKT_F} >"  "F")
    WRAP_TYPES("BNI${d}${ITKM_UL}" "itk::BandNode< itk::Index < ${d} >, ${ITKT_UL} >" "UL")
    WRAP_TYPES("BNI${d}${ITKM_US}" "itk::BandNode< itk::Index < ${d} >, ${ITKT_US} >" "US")
    WRAP_TYPES("BNI${d}${ITKM_UC}" "itk::BandNode< itk::Index < ${d} >, ${ITKT_UC} >" "UC")
    WRAP_TYPES("BNI${d}${ITKM_SL}" "itk::BandNode< itk::Index < ${d} >, ${ITKT_SL} >" "SL")
    WRAP_TYPES("BNI${d}${ITKM_SS}" "itk::BandNode< itk::Index < ${d} >, ${ITKT_SS} >" "SS")
    WRAP_TYPES("BNI${d}${ITKM_SC}" "itk::BandNode< itk::Index < ${d} >, ${ITKT_SC} >" "SC")
  ENDFOREACH(d)
END_WRAP_CLASS()
