
SET(itk_AutoInclude OFF)
WRAP_INCLUDE(NarrowBand)

WRAP_CLASS(BandNode)
  COND_WRAP("I3${ITKM_D}"  "itk::Index < 3 >, ${ITKT_D}"  "D")
  COND_WRAP("I3${ITKM_F}"  "itk::Index < 3 >, ${ITKT_F}"  "F")
  COND_WRAP("I3${ITKM_UL}" "itk::Index < 3 >, ${ITKT_UL}" "UL")
  COND_WRAP("I3${ITKM_US}" "itk::Index < 3 >, ${ITKT_US}" "US")
  COND_WRAP("I3${ITKM_UC}" "itk::Index < 3 >, ${ITKT_UC}" "UC")
  COND_WRAP("I3${ITKM_SL}" "itk::Index < 3 >, ${ITKT_SL}" "SL")
  COND_WRAP("I3${ITKM_SS}" "itk::Index < 3 >, ${ITKT_SS}" "SS")
  COND_WRAP("I3${ITKM_SC}" "itk::Index < 3 >, ${ITKT_SC}" "SC")

  COND_WRAP("I2${ITKM_D}"  "itk::Index < 2 >, ${ITKT_D}"  "D")
  COND_WRAP("I2${ITKM_F}"  "itk::Index < 2 >, ${ITKT_F}"  "F")
  COND_WRAP("I2${ITKM_UL}" "itk::Index < 2 >, ${ITKT_UL}" "UL")
  COND_WRAP("I2${ITKM_US}" "itk::Index < 2 >, ${ITKT_US}" "US")
  COND_WRAP("I2${ITKM_UC}" "itk::Index < 2 >, ${ITKT_UC}" "UC")
  COND_WRAP("I2${ITKM_SL}" "itk::Index < 2 >, ${ITKT_SL}" "SL")
  COND_WRAP("I2${ITKM_SS}" "itk::Index < 2 >, ${ITKT_SS}" "SS")
  COND_WRAP("I2${ITKM_SC}" "itk::Index < 2 >, ${ITKT_SC}" "SC")
END_WRAP_CLASS()

WRAP_CLASS(NarrowBand POINTER)
  COND_WRAP("BNI3${ITKM_D}"  "itk::BandNode< itk::Index < 3 >, ${ITKT_D} >"  "D")
  COND_WRAP("BNI3${ITKM_F}"  "itk::BandNode< itk::Index < 3 >, ${ITKT_F} >"  "F")
  COND_WRAP("BNI3${ITKM_UL}" "itk::BandNode< itk::Index < 3 >, ${ITKT_UL} >" "UL")
  COND_WRAP("BNI3${ITKM_US}" "itk::BandNode< itk::Index < 3 >, ${ITKT_US} >" "US")
  COND_WRAP("BNI3${ITKM_UC}" "itk::BandNode< itk::Index < 3 >, ${ITKT_UC} >" "UC")
  COND_WRAP("BNI3${ITKM_SL}" "itk::BandNode< itk::Index < 3 >, ${ITKT_SL} >" "SL")
  COND_WRAP("BNI3${ITKM_SS}" "itk::BandNode< itk::Index < 3 >, ${ITKT_SS} >" "SS")
  COND_WRAP("BNI3${ITKM_SC}" "itk::BandNode< itk::Index < 3 >, ${ITKT_SC} >" "SC")

  COND_WRAP("BNI2${ITKM_D}"  "itk::BandNode< itk::Index < 2 >, ${ITKT_D} >"  "D")
  COND_WRAP("BNI2${ITKM_F}"  "itk::BandNode< itk::Index < 2 >, ${ITKT_F} >"  "F")
  COND_WRAP("BNI2${ITKM_UL}" "itk::BandNode< itk::Index < 2 >, ${ITKT_UL} >" "UL")
  COND_WRAP("BNI2${ITKM_US}" "itk::BandNode< itk::Index < 2 >, ${ITKT_US} >" "US")
  COND_WRAP("BNI2${ITKM_UC}" "itk::BandNode< itk::Index < 2 >, ${ITKT_UC} >" "UC")
  COND_WRAP("BNI2${ITKM_SL}" "itk::BandNode< itk::Index < 2 >, ${ITKT_SL} >" "SL")
  COND_WRAP("BNI2${ITKM_SS}" "itk::BandNode< itk::Index < 2 >, ${ITKT_SS} >" "SS")
  COND_WRAP("BNI2${ITKM_SC}" "itk::BandNode< itk::Index < 2 >, ${ITKT_SC} >" "SC")
END_WRAP_CLASS()
