WRAP_CLASS("BinaryThresholdImageFilter" POINTER_WITH_SUPERCLASS)
  WRAP_INT(2)
  WRAP_SIGN_INT(2)
  WRAP_REAL(2)
  
  COND_WRAP("${ITKM_ID2}${ITKM_IF2}"  "${ITKT_ID2},${ITKT_IF2}"  "D;F")
  COND_WRAP("${ITKM_ID2}${ITKM_IUL2}" "${ITKT_ID2},${ITKT_IUL2}" "D;UL")
  COND_WRAP("${ITKM_ID2}${ITKM_IUS2}" "${ITKT_ID2},${ITKT_IUS2}" "D;US")
  COND_WRAP("${ITKM_ID2}${ITKM_IUC2}" "${ITKT_ID2},${ITKT_IUC2}" "D;UC")
  COND_WRAP("${ITKM_ID2}${ITKM_ISL2}" "${ITKT_ID2},${ITKT_ISL2}" "D;SL")
  COND_WRAP("${ITKM_ID2}${ITKM_ISS2}" "${ITKT_ID2},${ITKT_ISS2}" "D;SS")
  COND_WRAP("${ITKM_ID2}${ITKM_ISC2}" "${ITKT_ID2},${ITKT_ISC2}" "D;SC")
  
  COND_WRAP("${ITKM_IF2}${ITKM_IUL2}" "${ITKT_IF2},${ITKT_IUL2}" "F;UL")
  COND_WRAP("${ITKM_IF2}${ITKM_IUS2}" "${ITKT_IF2},${ITKT_IUS2}" "F;US")
  COND_WRAP("${ITKM_IF2}${ITKM_IUC2}" "${ITKT_IF2},${ITKT_IUC2}" "F;UC")
  COND_WRAP("${ITKM_IF2}${ITKM_ISL2}" "${ITKT_IF2},${ITKT_ISL2}" "F;SL")
  COND_WRAP("${ITKM_IF2}${ITKM_ISS2}" "${ITKT_IF2},${ITKT_ISS2}" "F;SS")
  COND_WRAP("${ITKM_IF2}${ITKM_ISC2}" "${ITKT_IF2},${ITKT_ISC2}" "F;SC")
  
  COND_WRAP("${ITKM_IUL2}${ITKM_IUS2}" "${ITKT_IUL2},${ITKT_IUS2}" "UL;US")
  COND_WRAP("${ITKM_IUL2}${ITKM_IUC2}" "${ITKT_IUL2},${ITKT_IUC2}" "UL;UC")
  COND_WRAP("${ITKM_IUL2}${ITKM_ISL2}" "${ITKT_IUL2},${ITKT_ISL2}" "UL;SL")
  COND_WRAP("${ITKM_IUL2}${ITKM_ISS2}" "${ITKT_IUL2},${ITKT_ISS2}" "UL;SS")
  COND_WRAP("${ITKM_IUL2}${ITKM_ISC2}" "${ITKT_IUL2},${ITKT_ISC2}" "UL;SC")
  
  COND_WRAP("${ITKM_IUS2}${ITKM_IUC2}" "${ITKT_IUS2},${ITKT_IUC2}" "US;UC")
  COND_WRAP("${ITKM_IUS2}${ITKM_ISC2}" "${ITKT_IUS2},${ITKT_ISC2}" "US;SC")
  
  COND_WRAP("${ITKM_ISL2}${ITKM_IUS2}" "${ITKT_ISL2},${ITKT_IUS2}" "SL;US")
  COND_WRAP("${ITKM_ISL2}${ITKM_IUC2}" "${ITKT_ISL2},${ITKT_IUC2}" "SL;UC")
  COND_WRAP("${ITKM_ISL2}${ITKM_ISS2}" "${ITKT_ISL2},${ITKT_ISS2}" "SL;SS")
  COND_WRAP("${ITKM_ISL2}${ITKM_ISC2}" "${ITKT_ISL2},${ITKT_ISC2}" "SL;SC")
  
  COND_WRAP("${ITKM_ISS2}${ITKM_IUC2}" "${ITKT_ISS2},${ITKT_IUC2}" "SS;UC")
  COND_WRAP("${ITKM_ISS2}${ITKM_ISC2}" "${ITKT_ISS2},${ITKT_ISC2}" "SS;SC")
  
  
  COND_WRAP("${ITKM_ID3}${ITKM_IF3}"  "${ITKT_ID3},${ITKT_IF3}"  "D;F")
  COND_WRAP("${ITKM_ID3}${ITKM_IUL3}" "${ITKT_ID3},${ITKT_IUL3}" "D;UL")
  COND_WRAP("${ITKM_ID3}${ITKM_IUS3}" "${ITKT_ID3},${ITKT_IUS3}" "D;US")
  COND_WRAP("${ITKM_ID3}${ITKM_IUC3}" "${ITKT_ID3},${ITKT_IUC3}" "D;UC")
  COND_WRAP("${ITKM_ID3}${ITKM_ISL3}" "${ITKT_ID3},${ITKT_ISL3}" "D;SL")
  COND_WRAP("${ITKM_ID3}${ITKM_ISS3}" "${ITKT_ID3},${ITKT_ISS3}" "D;SS")
  COND_WRAP("${ITKM_ID3}${ITKM_ISC3}" "${ITKT_ID3},${ITKT_ISC3}" "D;SC")
  
  COND_WRAP("${ITKM_IF3}${ITKM_IUL3}" "${ITKT_IF3},${ITKT_IUL3}" "F;UL")
  COND_WRAP("${ITKM_IF3}${ITKM_IUS3}" "${ITKT_IF3},${ITKT_IUS3}" "F;US")
  COND_WRAP("${ITKM_IF3}${ITKM_IUC3}" "${ITKT_IF3},${ITKT_IUC3}" "F;UC")
  COND_WRAP("${ITKM_IF3}${ITKM_ISL3}" "${ITKT_IF3},${ITKT_ISL3}" "F;SL")
  COND_WRAP("${ITKM_IF3}${ITKM_ISS3}" "${ITKT_IF3},${ITKT_ISS3}" "F;SS")
  COND_WRAP("${ITKM_IF3}${ITKM_ISC3}" "${ITKT_IF3},${ITKT_ISC3}" "F;SC")
  
  COND_WRAP("${ITKM_IUL3}${ITKM_IUS3}" "${ITKT_IUL3},${ITKT_IUS3}" "UL;US")
  COND_WRAP("${ITKM_IUL3}${ITKM_IUC3}" "${ITKT_IUL3},${ITKT_IUC3}" "UL;UC")
  COND_WRAP("${ITKM_IUL3}${ITKM_ISL3}" "${ITKT_IUL3},${ITKT_ISL3}" "UL;SL")
  COND_WRAP("${ITKM_IUL3}${ITKM_ISS3}" "${ITKT_IUL3},${ITKT_ISS3}" "UL;SS")
  COND_WRAP("${ITKM_IUL3}${ITKM_ISC3}" "${ITKT_IUL3},${ITKT_ISC3}" "UL;SC")
  
  COND_WRAP("${ITKM_IUS3}${ITKM_IUC3}" "${ITKT_IUS3},${ITKT_IUC3}" "US;UC")
  COND_WRAP("${ITKM_IUS3}${ITKM_ISC3}" "${ITKT_IUS3},${ITKT_ISC3}" "US;SC")
  
  COND_WRAP("${ITKM_ISL3}${ITKM_IUS3}" "${ITKT_ISL3},${ITKT_IUS3}" "SL;US")
  COND_WRAP("${ITKM_ISL3}${ITKM_IUC3}" "${ITKT_ISL3},${ITKT_IUC3}" "SL;UC")
  COND_WRAP("${ITKM_ISL3}${ITKM_ISS3}" "${ITKT_ISL3},${ITKT_ISS3}" "SL;SS")
  COND_WRAP("${ITKM_ISL3}${ITKM_ISC3}" "${ITKT_ISL3},${ITKT_ISC3}" "SL;SC")
  
  COND_WRAP("${ITKM_ISS3}${ITKM_IUC3}" "${ITKT_ISS3},${ITKT_IUC3}" "SS;UC")
  COND_WRAP("${ITKM_ISS3}${ITKM_ISC3}" "${ITKT_ISS3},${ITKT_ISC3}" "SS;SC")

END_WRAP_CLASS()
