WRAP_CLASS("ImageFileWriter" POINTER)
  FOREACH(d ${WRAP_DIMS})
    COND_WRAP("${ITKM_IF${d}}"  "${ITKT_IF${d}}"  "F")
    COND_WRAP("${ITKM_ID${d}}"  "${ITKT_ID${d}}"  "D")
    COND_WRAP("${ITKM_IUC${d}}" "${ITKT_IUC${d}}" "")  # neded to save in 8 bits
    COND_WRAP("${ITKM_IUS${d}}" "${ITKT_IUS${d}}" "US")
    COND_WRAP("${ITKM_IUL${d}}" "${ITKT_IUL${d}}" "UL")
    COND_WRAP("${ITKM_ISC${d}}" "${ITKT_ISC${d}}" "SC")
    COND_WRAP("${ITKM_ISS${d}}" "${ITKT_ISS${d}}" "SS")
    COND_WRAP("${ITKM_ISL${d}}" "${ITKT_ISL${d}}" "SL")
  ENDFOREACH(d)
END_WRAP_CLASS()
