WRAP_CLASS("itk::MeanReciprocalSquareDifferenceImageToImageMetric" POINTER)

  WRAP_IMAGE_FILTER_INT_FOR_DIMS(2 2+)
  WRAP_IMAGE_FILTER_SIGN_INT_FOR_DIMS(2 2+)
  WRAP_IMAGE_FILTER_REAL_FOR_DIMS(2 2+)

END_WRAP_CLASS()
