WRAP_CLASS("ConnectedComponentImageFilter" POINTER)

  COND_WRAP("${ITKM_IUL2}${ITKM_IUL2}" "${ITKT_IUL2},${ITKT_IUL2}" "UL")
  
  COND_WRAP("${ITKM_IUS2}${ITKM_IUL2}" "${ITKT_IUS2},${ITKT_IUL2}" "US") # needed for watershed
  COND_WRAP("${ITKM_IUS2}${ITKM_IUS2}" "${ITKT_IUS2},${ITKT_IUS2}" "US")
  COND_WRAP("${ITKM_IUS2}${ITKM_ISL2}" "${ITKT_IUS2},${ITKT_ISL2}" "US;SL")
  
  COND_WRAP("${ITKM_IUC2}${ITKM_IUL2}" "${ITKT_IUC2},${ITKT_IUL2}" "UC") # needed for watershed
  COND_WRAP("${ITKM_IUC2}${ITKM_IUS2}" "${ITKT_IUC2},${ITKT_IUS2}" "UC;US")
  COND_WRAP("${ITKM_IUC2}${ITKM_IUC2}" "${ITKT_IUC2},${ITKT_IUC2}" "UC")
  COND_WRAP("${ITKM_IUC2}${ITKM_ISL2}" "${ITKT_IUC2},${ITKT_ISL2}" "UC;SL")
  COND_WRAP("${ITKM_IUC2}${ITKM_ISS2}" "${ITKT_IUC2},${ITKT_ISS2}" "UC;SS")
  
  COND_WRAP("${ITKM_ISL2}${ITKM_IUL2}" "${ITKT_ISL2},${ITKT_IUL2}" "SL") # needed for watershed
  COND_WRAP("${ITKM_ISL2}${ITKM_ISL2}" "${ITKT_ISL2},${ITKT_ISL2}" "SL")
  
  COND_WRAP("${ITKM_ISS2}${ITKM_IUL2}" "${ITKT_ISS2},${ITKT_IUL2}" "SS") # needed for watershed
  COND_WRAP("${ITKM_ISS2}${ITKM_IUS2}" "${ITKT_ISS2},${ITKT_IUS2}" "SS;US")
  COND_WRAP("${ITKM_ISS2}${ITKM_ISL2}" "${ITKT_ISS2},${ITKT_ISL2}" "SS;SL")
  COND_WRAP("${ITKM_ISS2}${ITKM_ISS2}" "${ITKT_ISS2},${ITKT_ISS2}" "SS")
  
  COND_WRAP("${ITKM_ISC2}${ITKM_IUL2}" "${ITKT_ISC2},${ITKT_IUL2}" "SC") # needed for watershed
  COND_WRAP("${ITKM_ISC2}${ITKM_IUS2}" "${ITKT_ISC2},${ITKT_IUS2}" "SC;US")
  COND_WRAP("${ITKM_ISC2}${ITKM_IUC2}" "${ITKT_ISC2},${ITKT_IUC2}" "SC;UC")
  COND_WRAP("${ITKM_ISC2}${ITKM_ISL2}" "${ITKT_ISC2},${ITKT_ISL2}" "SC;SL")
  COND_WRAP("${ITKM_ISC2}${ITKM_ISS2}" "${ITKT_ISC2},${ITKT_ISS2}" "SC;SS")
  COND_WRAP("${ITKM_ISC2}${ITKM_ISC2}" "${ITKT_ISC2},${ITKT_ISC2}" "SC")
  
  
  COND_WRAP("${ITKM_IUL3}${ITKM_IUL3}" "${ITKT_IUL3},${ITKT_IUL3}" "UL")
  
  COND_WRAP("${ITKM_IUS3}${ITKM_IUL3}" "${ITKT_IUS3},${ITKT_IUL3}" "US") # needed for watershed
  COND_WRAP("${ITKM_IUS3}${ITKM_IUS3}" "${ITKT_IUS3},${ITKT_IUS3}" "US")
  COND_WRAP("${ITKM_IUS3}${ITKM_ISL3}" "${ITKT_IUS3},${ITKT_ISL3}" "US;SL")
  
  COND_WRAP("${ITKM_IUC3}${ITKM_IUL3}" "${ITKT_IUC3},${ITKT_IUL3}" "UC") # needed for watershed
  COND_WRAP("${ITKM_IUC3}${ITKM_IUS3}" "${ITKT_IUC3},${ITKT_IUS3}" "UC;US")
  COND_WRAP("${ITKM_IUC3}${ITKM_IUC3}" "${ITKT_IUC3},${ITKT_IUC3}" "UC")
  COND_WRAP("${ITKM_IUC3}${ITKM_ISL3}" "${ITKT_IUC3},${ITKT_ISL3}" "UC;SL")
  COND_WRAP("${ITKM_IUC3}${ITKM_ISS3}" "${ITKT_IUC3},${ITKT_ISS3}" "UC;SS")
  
  COND_WRAP("${ITKM_ISL3}${ITKM_IUL3}" "${ITKT_ISL3},${ITKT_IUL3}" "SL") # needed for watershed
  COND_WRAP("${ITKM_ISL3}${ITKM_ISL3}" "${ITKT_ISL3},${ITKT_ISL3}" "SL")
  
  COND_WRAP("${ITKM_ISS3}${ITKM_IUL3}" "${ITKT_ISS3},${ITKT_IUL3}" "SS") # needed for watershed
  COND_WRAP("${ITKM_ISS3}${ITKM_IUS3}" "${ITKT_ISS3},${ITKT_IUS3}" "SS;US")
  COND_WRAP("${ITKM_ISS3}${ITKM_ISL3}" "${ITKT_ISS3},${ITKT_ISL3}" "SS;SL")
  COND_WRAP("${ITKM_ISS3}${ITKM_ISS3}" "${ITKT_ISS3},${ITKT_ISS3}" "SS")
  
  COND_WRAP("${ITKM_ISC3}${ITKM_IUL3}" "${ITKT_ISC3},${ITKT_IUL3}" "SC") # needed for watershed
  COND_WRAP("${ITKM_ISC3}${ITKM_IUS3}" "${ITKT_ISC3},${ITKT_IUS3}" "SC;US")
  COND_WRAP("${ITKM_ISC3}${ITKM_IUC3}" "${ITKT_ISC3},${ITKT_IUC3}" "SC;UC")
  COND_WRAP("${ITKM_ISC3}${ITKM_ISL3}" "${ITKT_ISC3},${ITKT_ISL3}" "SC;SL")
  COND_WRAP("${ITKM_ISC3}${ITKM_ISS3}" "${ITKT_ISC3},${ITKT_ISS3}" "SC;SS")
  COND_WRAP("${ITKM_ISC3}${ITKM_ISC3}" "${ITKT_ISC3},${ITKT_ISC3}" "SC")

END_WRAP_CLASS()
