WRAP_CLASS("itk::VectorContainer" POINTER)
  FOREACH(d ${WRAP_ITK_DIMS})
    WRAP("${ITKM_UI}${ITKM_LSNF${d}}"  "${ITKT_UI},${ITKT_LSNF${d}}")
    WRAP("${ITKM_UI}${ITKM_LSND${d}}"  "${ITKT_UI},${ITKT_LSND${d}}")
    WRAP("${ITKM_UI}${ITKM_LSNUC${d}}" "${ITKT_UI},${ITKT_LSNUC${d}}")
    WRAP("${ITKM_UI}${ITKM_LSNUS${d}}" "${ITKT_UI},${ITKT_LSNUS${d}}")
    WRAP("${ITKM_UI}${ITKM_LSNUL${d}}" "${ITKT_UI},${ITKT_LSNUL${d}}")
    WRAP("${ITKM_UI}${ITKM_LSNSC${d}}" "${ITKT_UI},${ITKT_LSNSC${d}}")
    WRAP("${ITKM_UI}${ITKM_LSNSS${d}}" "${ITKT_UI},${ITKT_LSNSS${d}}")
    WRAP("${ITKM_UI}${ITKM_LSNSL${d}}" "${ITKT_UI},${ITKT_LSNSL${d}}")
    WRAP("${ITKM_UL}${ITKM_VD${d}}"    "${ITKT_UL},${ITKT_VD${d}}")
  ENDFOREACH(d)
END_WRAP_CLASS()
