WRAP_CLASS_NOTPL("Command"            POINTER)
WRAP_CLASS_NOTPL("DataObject"         POINTER)
WRAP_CLASS_NOTPL("Directory"          POINTER)
WRAP_CLASS_NOTPL("DynamicLoader"      POINTER)
WRAP_CLASS_NOTPL("LightObject"        POINTER)
WRAP_CLASS_NOTPL("Object"             POINTER)
WRAP_CLASS_NOTPL("ObjectFactoryBase"  POINTER)
WRAP_CLASS_NOTPL("LightProcessObject" POINTER)
WRAP_CLASS_NOTPL("ProcessObject"      POINTER)
WRAP_CLASS_NOTPL("OutputWindow"       POINTER)
WRAP_CLASS_NOTPL("Version"            POINTER)
WRAP_CLASS_NOTPL("MultiThreader"      POINTER)
WRAP_CLASS_NOTPL("TimeStamp")
WRAP_CLASS_NOTPL("Indent")
WRAP_CLASS_NOTPL("StringStream")
WRAP_CLASS_NOTPL("MetaDataDictionary")
