WRAP_CLASS("itk::ImageBase" POINTER)
  FOREACH(d ${WRAP_DIMS})
    WRAP("${d}"  "${d}")
  ENDFOREACH(d)
END_WRAP_CLASS()

WRAP_CLASS("itk::Image" POINTER)
  SET(WRAPPER_TEMPLATES "${itk_Wrap_Image}")
END_WRAP_CLASS()
