INTERSECTION(interpolator_types "F;US" "${WRAP_ITK_SCALAR}")

WRAP_CLASS("itk::InterpolateImageFunction" POINTER)
  FOREACH(d ${WRAP_ITK_DIMS})
    FOREACH(t ${interpolator_types})
      WRAP_TEMPLATE("${ITKM_I${t}${d}}${ITKM_D}" "${ITKT_I${t}${d}},${ITKT_D}")    
    ENDFOREACH(t)
  ENDFOREACH(d)
END_WRAP_CLASS()

WRAP_CLASS("itk::LinearInterpolateImageFunction" POINTER)
  FOREACH(d ${WRAP_ITK_DIMS})
    FOREACH(t ${interpolator_types})
      WRAP_TEMPLATE("${ITKM_I${t}${d}}${ITKM_D}" "${ITKT_I${t}${d}},${ITKT_D}")    
    ENDFOREACH(t)
  ENDFOREACH(d)
END_WRAP_CLASS()

WRAP_CLASS("itk::NearestNeighborInterpolateImageFunction" POINTER)
  FOREACH(d ${WRAP_ITK_DIMS})
    FOREACH(t ${interpolator_types})
      WRAP_TEMPLATE("${ITKM_I${t}${d}}${ITKM_D}" "${ITKT_I${t}${d}},${ITKT_D}")    
    ENDFOREACH(t)
  ENDFOREACH(d)
END_WRAP_CLASS()

WRAP_CLASS("itk::BSplineInterpolateImageFunction" POINTER)
  FOREACH(d ${WRAP_ITK_DIMS})
    FOREACH(t ${interpolator_types})
      WRAP_TEMPLATE("${ITKM_I${t}${d}}${ITKM_D}" "${ITKT_I${t}${d}},${ITKT_D}")
      WRAP_TEMPLATE("${ITKM_I${t}${d}}${ITKM_D}${ITKM_${t}}" "${ITKT_I${t}${d}},${ITKT_D},${ITKT_${t}}")
    ENDFOREACH(t)
  ENDFOREACH(d)
END_WRAP_CLASS()

WRAP_CLASS("itk::BSplineResampleImageFunction" POINTER)
  FOREACH(d ${WRAP_ITK_DIMS})
    FOREACH(t ${interpolator_types})
      WRAP_TEMPLATE("${ITKM_I${t}${d}}${ITKM_D}" "${ITKT_I${t}${d}},${ITKT_D}")    
    ENDFOREACH(t)
  ENDFOREACH(d)
END_WRAP_CLASS()
