WRAP_CLASS("ImageFunction" POINTER)
  FOREACH(d ${WRAP_DIMS})
    COND_WRAP("${ITKM_ID${d}}${ITKM_D}${ITKM_F}"  "${ITKT_ID${d}},${ITKT_D},${ITKT_F}" "D")
    COND_WRAP("${ITKM_IF${d}}${ITKM_D}${ITKM_F}"  "${ITKT_IF${d}},${ITKT_D},${ITKT_F}"  "F")
    COND_WRAP("${ITKM_IUL${d}}${ITKM_D}${ITKM_F}" "${ITKT_IUL${d}},${ITKT_D},${ITKT_F}" "UL")
    COND_WRAP("${ITKM_IUS${d}}${ITKM_D}${ITKM_F}" "${ITKT_IUS${d}},${ITKT_D},${ITKT_F}" "US")
    COND_WRAP("${ITKM_IUC${d}}${ITKM_D}${ITKM_F}" "${ITKT_IUC${d}},${ITKT_D},${ITKT_F}" "UC")
    COND_WRAP("${ITKM_ISL${d}}${ITKM_D}${ITKM_F}" "${ITKT_ISL${d}},${ITKT_D},${ITKT_F}" "SL")
    COND_WRAP("${ITKM_ISS${d}}${ITKM_D}${ITKM_F}" "${ITKT_ISS${d}},${ITKT_D},${ITKT_F}" "SS")
    COND_WRAP("${ITKM_ISC${d}}${ITKM_D}${ITKM_F}" "${ITKT_ISC${d}},${ITKT_D},${ITKT_F}" "SC")
    
    COND_WRAP("${ITKM_ID${d}}${ITKM_D}${ITKM_D}"  "${ITKT_ID${d}},${ITKT_D},${ITKT_D}" "D")
    COND_WRAP("${ITKM_IF${d}}${ITKM_D}${ITKM_D}"  "${ITKT_IF${d}},${ITKT_D},${ITKT_D}"  "F")
    COND_WRAP("${ITKM_IUL${d}}${ITKM_D}${ITKM_D}" "${ITKT_IUL${d}},${ITKT_D},${ITKT_D}" "UL")
    COND_WRAP("${ITKM_IUS${d}}${ITKM_D}${ITKM_D}" "${ITKT_IUS${d}},${ITKT_D},${ITKT_D}" "US")
    COND_WRAP("${ITKM_IUC${d}}${ITKM_D}${ITKM_D}" "${ITKT_IUC${d}},${ITKT_D},${ITKT_D}" "UC")
    COND_WRAP("${ITKM_ISL${d}}${ITKM_D}${ITKM_D}" "${ITKT_ISL${d}},${ITKT_D},${ITKT_D}" "SL")
    COND_WRAP("${ITKM_ISS${d}}${ITKM_D}${ITKM_D}" "${ITKT_ISS${d}},${ITKT_D},${ITKT_D}" "SS")
    COND_WRAP("${ITKM_ISC${d}}${ITKM_D}${ITKM_D}" "${ITKT_ISC${d}},${ITKT_D},${ITKT_D}" "SC")
  ENDFOREACH(d)
END_WRAP_CLASS()
