# auto include feature must be disable because all the following classes are in the same file
SET(itk_AutoInclude OFF)
WRAP_INCLUDE(EventObject)

WRAP_CLASS_NOTPL("EventObject")
WRAP_CLASS_NOTPL("NoEvent")
WRAP_CLASS_NOTPL("AnyEvent")
WRAP_CLASS_NOTPL("DeleteEvent")
WRAP_CLASS_NOTPL("StartEvent")
WRAP_CLASS_NOTPL("EndEvent")
WRAP_CLASS_NOTPL("ProgressEvent")
WRAP_CLASS_NOTPL("ExitEvent")
WRAP_CLASS_NOTPL("ModifiedEvent")
WRAP_CLASS_NOTPL("IterationEvent")
WRAP_CLASS_NOTPL("PickEvent")
WRAP_CLASS_NOTPL("StartPickEvent")
WRAP_CLASS_NOTPL("EndPickEvent")
WRAP_CLASS_NOTPL("AbortCheckEvent")
WRAP_CLASS_NOTPL("UserEvent")
