WRAP_CLASS("ImageToImageFilter" POINTER)
  COND_WRAP("${ITKM_ID3}${ITKM_ID3}"  "${ITKT_ID3},${ITKT_ID3}"  "D")
  COND_WRAP("${ITKM_ID3}${ITKM_IF3}"  "${ITKT_ID3},${ITKT_IF3}"  "D;F")
  COND_WRAP("${ITKM_ID3}${ITKM_IUL3}" "${ITKT_ID3},${ITKT_IUL3}" "D") # needed for watershed
  COND_WRAP("${ITKM_ID3}${ITKM_IUS3}" "${ITKT_ID3},${ITKT_IUS3}" "D;US")
  COND_WRAP("${ITKM_ID3}${ITKM_IUC3}" "${ITKT_ID3},${ITKT_IUC3}" "D") # needed to save in 8 bits
  COND_WRAP("${ITKM_ID3}${ITKM_ISL3}" "${ITKT_ID3},${ITKT_ISL3}" "D;SL")
  COND_WRAP("${ITKM_ID3}${ITKM_ISS3}" "${ITKT_ID3},${ITKT_ISS3}" "D;SS")
  COND_WRAP("${ITKM_ID3}${ITKM_ISC3}" "${ITKT_ID3},${ITKT_ISC3}" "D;SC")
  
  COND_WRAP("${ITKM_IF3}${ITKM_ID3}"  "${ITKT_IF3},${ITKT_ID3}"  "F;D")
  COND_WRAP("${ITKM_IF3}${ITKM_IF3}"  "${ITKT_IF3},${ITKT_IF3}"  "F")
  COND_WRAP("${ITKM_IF3}${ITKM_IUL3}" "${ITKT_IF3},${ITKT_IUL3}" "F") # needed for watershed
  COND_WRAP("${ITKM_IF3}${ITKM_IUS3}" "${ITKT_IF3},${ITKT_IUS3}" "F;US")
  COND_WRAP("${ITKM_IF3}${ITKM_IUC3}" "${ITKT_IF3},${ITKT_IUC3}" "F") # needed to save in 8 bits
  COND_WRAP("${ITKM_IF3}${ITKM_ISL3}" "${ITKT_IF3},${ITKT_ISL3}" "F;SL")
  COND_WRAP("${ITKM_IF3}${ITKM_ISS3}" "${ITKT_IF3},${ITKT_ISS3}" "F;SS")
  COND_WRAP("${ITKM_IF3}${ITKM_ISC3}" "${ITKT_IF3},${ITKT_ISC3}" "F;SC")
  
  COND_WRAP("${ITKM_IUL3}${ITKM_ID3}"  "${ITKT_IUL3},${ITKT_ID3}"  "UL;D")
  COND_WRAP("${ITKM_IUL3}${ITKM_IF3}"  "${ITKT_IUL3},${ITKT_IF3}"  "UL;F")
  COND_WRAP("${ITKM_IUL3}${ITKM_IUL3}" "${ITKT_IUL3},${ITKT_IUL3}" "UL")
  COND_WRAP("${ITKM_IUL3}${ITKM_IUS3}" "${ITKT_IUL3},${ITKT_IUS3}" "US") # needed for relabel component
  COND_WRAP("${ITKM_IUL3}${ITKM_IUC3}" "${ITKT_IUL3},${ITKT_IUC3}" "") # needed to save in 8 bits and for relabel component
  COND_WRAP("${ITKM_IUL3}${ITKM_ISL3}" "${ITKT_IUL3},${ITKT_ISL3}" "SL") # needed for relabel component
  COND_WRAP("${ITKM_IUL3}${ITKM_ISS3}" "${ITKT_IUL3},${ITKT_ISS3}" "SS") # needed for relabel component
  COND_WRAP("${ITKM_IUL3}${ITKM_ISC3}" "${ITKT_IUL3},${ITKT_ISC3}" "SC") # needed for relabel component
  
  COND_WRAP("${ITKM_IUS3}${ITKM_ID3}"  "${ITKT_IUS3},${ITKT_ID3}"  "US;D")
  COND_WRAP("${ITKM_IUS3}${ITKM_IF3}"  "${ITKT_IUS3},${ITKT_IF3}"  "US;F")
  COND_WRAP("${ITKM_IUS3}${ITKM_IUL3}" "${ITKT_IUS3},${ITKT_IUL3}" "US") # needed for watershed
  COND_WRAP("${ITKM_IUS3}${ITKM_IUS3}" "${ITKT_IUS3},${ITKT_IUS3}" "US")
  COND_WRAP("${ITKM_IUS3}${ITKM_IUC3}" "${ITKT_IUS3},${ITKT_IUC3}" "US") # needed to save in 8 bits
  COND_WRAP("${ITKM_IUS3}${ITKM_ISL3}" "${ITKT_IUS3},${ITKT_ISL3}" "US;SL")
  COND_WRAP("${ITKM_IUS3}${ITKM_ISS3}" "${ITKT_IUS3},${ITKT_ISS3}" "US;SS")
  COND_WRAP("${ITKM_IUS3}${ITKM_ISC3}" "${ITKT_IUS3},${ITKT_ISC3}" "US;SC")
  
  COND_WRAP("${ITKM_IUC3}${ITKM_ID3}"  "${ITKT_IUC3},${ITKT_ID3}"  "UC;D")
  COND_WRAP("${ITKM_IUC3}${ITKM_IF3}"  "${ITKT_IUC3},${ITKT_IF3}"  "UC;F")
  COND_WRAP("${ITKM_IUC3}${ITKM_IUL3}" "${ITKT_IUC3},${ITKT_IUL3}" "UC") # needed for watershed
  COND_WRAP("${ITKM_IUC3}${ITKM_IUS3}" "${ITKT_IUC3},${ITKT_IUS3}" "UC;US")
  COND_WRAP("${ITKM_IUC3}${ITKM_IUC3}" "${ITKT_IUC3},${ITKT_IUC3}" "UC")
  COND_WRAP("${ITKM_IUC3}${ITKM_ISL3}" "${ITKT_IUC3},${ITKT_ISL3}" "UC;SL")
  COND_WRAP("${ITKM_IUC3}${ITKM_ISS3}" "${ITKT_IUC3},${ITKT_ISS3}" "UC;SS")
  COND_WRAP("${ITKM_IUC3}${ITKM_ISC3}" "${ITKT_IUC3},${ITKT_ISC3}" "UC;SC")
  
  COND_WRAP("${ITKM_ISL3}${ITKM_ID3}"  "${ITKT_ISL3},${ITKT_ID3}"  "SL;D")
  COND_WRAP("${ITKM_ISL3}${ITKM_IF3}"  "${ITKT_ISL3},${ITKT_IF3}"  "SL;F")
  COND_WRAP("${ITKM_ISL3}${ITKM_IUL3}" "${ITKT_ISL3},${ITKT_IUL3}" "SL") # needed for watershed
  COND_WRAP("${ITKM_ISL3}${ITKM_IUS3}" "${ITKT_ISL3},${ITKT_IUS3}" "SL;US")
  COND_WRAP("${ITKM_ISL3}${ITKM_IUC3}" "${ITKT_ISL3},${ITKT_IUC3}" "SL") # needed to save in 8 bits
  COND_WRAP("${ITKM_ISL3}${ITKM_ISL3}" "${ITKT_ISL3},${ITKT_ISL3}" "SL")
  COND_WRAP("${ITKM_ISL3}${ITKM_ISS3}" "${ITKT_ISL3},${ITKT_ISS3}" "SL;SS")
  COND_WRAP("${ITKM_ISL3}${ITKM_ISC3}" "${ITKT_ISL3},${ITKT_ISC3}" "SL;SC")
  
  COND_WRAP("${ITKM_ISS3}${ITKM_ID3}"  "${ITKT_ISS3},${ITKT_ID3}"  "SS;D")
  COND_WRAP("${ITKM_ISS3}${ITKM_IF3}"  "${ITKT_ISS3},${ITKT_IF3}"  "SS;F")
  COND_WRAP("${ITKM_ISS3}${ITKM_IUL3}" "${ITKT_ISS3},${ITKT_IUL3}" "SS") # needed for watershed
  COND_WRAP("${ITKM_ISS3}${ITKM_IUS3}" "${ITKT_ISS3},${ITKT_IUS3}" "SS;US")
  COND_WRAP("${ITKM_ISS3}${ITKM_IUC3}" "${ITKT_ISS3},${ITKT_IUC3}" "SS") # needed to save in 8 bits
  COND_WRAP("${ITKM_ISS3}${ITKM_ISL3}" "${ITKT_ISS3},${ITKT_ISL3}" "SS;SL")
  COND_WRAP("${ITKM_ISS3}${ITKM_ISS3}" "${ITKT_ISS3},${ITKT_ISS3}" "SS")
  COND_WRAP("${ITKM_ISS3}${ITKM_ISC3}" "${ITKT_ISS3},${ITKT_ISC3}" "SS;SC")
  
  COND_WRAP("${ITKM_ISC3}${ITKM_ID3}"  "${ITKT_ISC3},${ITKT_ID3}"  "SC;D")
  COND_WRAP("${ITKM_ISC3}${ITKM_IF3}"  "${ITKT_ISC3},${ITKT_IF3}"  "SC;F")
  COND_WRAP("${ITKM_ISC3}${ITKM_IUL3}" "${ITKT_ISC3},${ITKT_IUL3}" "SC") # needed for watershed
  COND_WRAP("${ITKM_ISC3}${ITKM_IUS3}" "${ITKT_ISC3},${ITKT_IUS3}" "SC;US")
  COND_WRAP("${ITKM_ISC3}${ITKM_IUC3}" "${ITKT_ISC3},${ITKT_IUC3}" "SC") # needed to save in 8 bits
  COND_WRAP("${ITKM_ISC3}${ITKM_ISL3}" "${ITKT_ISC3},${ITKT_ISL3}" "SC;SL")
  COND_WRAP("${ITKM_ISC3}${ITKM_ISS3}" "${ITKT_ISC3},${ITKT_ISS3}" "SC;SS")
  COND_WRAP("${ITKM_ISC3}${ITKM_ISC3}" "${ITKT_ISC3},${ITKT_ISC3}" "SC")
  
  # dim=2 -> dim=3
  COND_WRAP("${ITKM_ID2}${ITKM_ID3}"   "${ITKT_ID2},${ITKT_ID3}"   "D")
  COND_WRAP("${ITKM_IF2}${ITKM_IF3}"   "${ITKT_IF2},${ITKT_IF3}"   "F")
  COND_WRAP("${ITKM_IUL2}${ITKM_IUL3}" "${ITKT_IUL2},${ITKT_IUL3}" "UL")
  COND_WRAP("${ITKM_IUS2}${ITKM_IUS3}" "${ITKT_IUS2},${ITKT_IUS3}" "US")
  COND_WRAP("${ITKM_IUC2}${ITKM_IUC3}" "${ITKT_IUC2},${ITKT_IUC3}" "UC")
  COND_WRAP("${ITKM_ISL2}${ITKM_ISL3}" "${ITKT_ISL2},${ITKT_ISL3}" "SL")
  COND_WRAP("${ITKM_ISS2}${ITKM_ISS3}" "${ITKT_ISS2},${ITKT_ISS3}" "SS")
  COND_WRAP("${ITKM_ISC2}${ITKM_ISC3}" "${ITKT_ISC2},${ITKT_ISC3}" "SC")
  
  # vector types
  COND_WRAP("${ITKM_IVD33}${ITKM_IVD33}"  "${ITKT_IVD33},${ITKT_IVD33}"  "VD")
  COND_WRAP("${ITKM_IVF33}${ITKM_IVF33}"  "${ITKT_IVF33},${ITKT_IVF33}"  "VF")
  COND_WRAP("${ITKM_ICVD33}${ITKM_ICVD33}"  "${ITKT_ICVD33},${ITKT_ICVD33}"  "CVD")
  COND_WRAP("${ITKM_ICVF33}${ITKM_ICVF33}"  "${ITKT_ICVF33},${ITKT_ICVF33}"  "CVF")
END_WRAP_CLASS()

