WRAP_CLASS("itk::Neighborhood")
  FOREACH(d ${WRAP_ITK_DIMS})
    FOREACH(t ${WRAP_ITK_SCALAR} ${WRAP_ITK_RGB})
      WRAP_TEMPLATE("${ITKM_${t}}${d}" "${ITKT_${t}},${d}")   
    ENDFOREACH(t)

    FOREACH(t ${WRAP_ITK_VECTOR})
      WRAP_TEMPLATE("${ITKM_${t}${d}}${d}" "${ITKT_${t}${d}},${d}")   
    ENDFOREACH(t)
  ENDFOREACH(d)
END_WRAP_CLASS()
