WRAP_CLASS("SimpleDataObjectDecorator" POINTER)
  WRAP("${ITKM_D}"   "${ITKT_D}")
  WRAP("${ITKM_F}"   "${ITKT_F}")
  WRAP("${ITKM_UL}"  "${ITKT_UL}")
  WRAP("${ITKM_US}"  "${ITKT_US}")
  WRAP("${ITKM_UC}"  "${ITKT_UC}")
  WRAP("${ITKM_SL}"  "${ITKT_SL}")
  WRAP("${ITKM_SS}"  "${ITKT_SS}")
  WRAP("${ITKM_SC}"  "${ITKT_SC}")
  WRAP("${ITKM_B}"   "${ITKT_B}")
END_WRAP_CLASS()
