WRAP_CLASS("KernelTransform" POINTER)
  FOREACH(d ${WRAP_DIMS})
    WRAP("${ITKM_D}${d}" "${ITKT_D},${d}")
  ENDFOREACH(d)
END_WRAP_CLASS()

WRAP_CLASS("ElasticBodyReciprocalSplineKernelTransform" POINTER)
  FOREACH(d ${WRAP_DIMS})
    WRAP("${ITKM_D}${d}" "${ITKT_D},${d}")
  ENDFOREACH(d)
END_WRAP_CLASS()

WRAP_CLASS("ElasticBodySplineKernelTransform" POINTER)
  FOREACH(d ${WRAP_DIMS})
    WRAP("${ITKM_D}${d}" "${ITKT_D},${d}")
  ENDFOREACH(d)
END_WRAP_CLASS()

WRAP_CLASS("ThinPlateR2LogRSplineKernelTransform" POINTER)
  FOREACH(d ${WRAP_DIMS})
    WRAP("${ITKM_D}${d}" "${ITKT_D},${d}")
  ENDFOREACH(d)
END_WRAP_CLASS()

WRAP_CLASS("ThinPlateSplineKernelTransform" POINTER)
  FOREACH(d ${WRAP_DIMS})
    WRAP("${ITKM_D}${d}" "${ITKT_D},${d}")
  ENDFOREACH(d)
END_WRAP_CLASS()

WRAP_CLASS("VolumeSplineKernelTransform" POINTER)
  FOREACH(d ${WRAP_DIMS})
    WRAP("${ITKM_D}${d}" "${ITKT_D},${d}")
  ENDFOREACH(d)
END_WRAP_CLASS()
