WRAP_CLASS("ScaleTransform" POINTER)
  FOREACH(d ${WRAP_DIMS})
    WRAP("${ITKM_D}${d}" "${ITKT_D},${d}")
  ENDFOREACH(d)
END_WRAP_CLASS()

WRAP_CLASS("ScaleLogarithmicTransform" POINTER)
  FOREACH(d ${WRAP_DIMS})
    WRAP("${ITKM_D}${d}" "${ITKT_D},${d}")
  ENDFOREACH(d)
END_WRAP_CLASS()
